In [1]:
# read in already cleaned/matched data from previous code

import sys
import os
import xlrd as xl
import pandas as pd
import openpyxl
import numpy as np
from openpyxl import load_workbook
from pandas import ExcelWriter
import six
import time
import pathlib
import copy
import numpy.matlib 


from pathlib import Path
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.datasets.samples_generator import make_blobs
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

from scipy.spatial import distance


os.chdir(r"C:\Users\gjhaa\Desktop\Masters_Project\Gene File Manipulations\Gene_Data\Isolated_Gene_Data\Cleaned_Data\Matched_Data")
path = os.getcwd()
filepath=os.getcwd()
files = os.listdir(u'.')

print("\n\n")

print("\n\n")
k=1

files = [f for f in files if f[-3:] == 'txt']

print(files)

SetIntersection=[]

for i in range(len(files)):
    
    filename = files[i]
    print("Filename : " +str(filename))
    print("File Path : " + str(path))

    
    num_lines = sum(1 for line in open(filename))
    f=open(filename,"r")


    print("Total Lines in File : " +str(num_lines))
    #print("\n\n")
  
    lines=f.readlines()
    
    
    if(k==4):
        class4 = np.loadtxt(lines, delimiter=',')
        k=5
    
    if(k==3):
        class3 = np.loadtxt(lines, delimiter=',')
        k=4
    
    if(k==2):
        class2 = np.loadtxt(lines, delimiter=',')
        k=3
    
    if(k==1):
        class1 = np.loadtxt(lines, delimiter=',')
        k=2
                        
    f.close()

    

albanian = class1.T  # FRENCH
greek = class2.T     #GREEK
japanese=class3.T    #IRANIAN
korean=class4.T      #SPANISH
print(np.shape(greek))
print(np.shape(albanian))
print(np.shape(japanese))
print(np.shape(korean))







['Albania_Region_Data.txt', 'Greek_Region_Data.txt', 'Japanese_Region_Data.txt', 'korean_Region_Data.txt']
Filename : Albania_Region_Data.txt
File Path : C:\Users\gjhaa\Desktop\Masters_Project\Gene File Manipulations\Gene_Data\Isolated_Gene_Data\Cleaned_Data\Matched_Data
Total Lines in File : 604184
Filename : Greek_Region_Data.txt
File Path : C:\Users\gjhaa\Desktop\Masters_Project\Gene File Manipulations\Gene_Data\Isolated_Gene_Data\Cleaned_Data\Matched_Data
Total Lines in File : 604184
Filename : Japanese_Region_Data.txt
File Path : C:\Users\gjhaa\Desktop\Masters_Project\Gene File Manipulations\Gene_Data\Isolated_Gene_Data\Cleaned_Data\Matched_Data
Total Lines in File : 604184
Filename : korean_Region_Data.txt
File Path : C:\Users\gjhaa\Desktop\Masters_Project\Gene File Manipulations\Gene_Data\Isolated_Gene_Data\Cleaned_Data\Matched_Data
Total Lines in File : 604184
(20, 604184)
(6, 604184)
(29, 604184)
(6, 604184)


In [6]:
#calculate T1 statistics

#related if t1 > 2/3
#unrelated and from same populations t1 = 2/3
#different populations if t1 < 2/3

combined_data=np.vstack((albanian,greek,japanese,korean))
print("\nShape of Combined Data is " + str(np.shape(combined_data)))
print("\n")

num_ind = combined_data.shape[0]
num_chromosomes = combined_data.shape[1]
num_distances = num_ind*num_ind

t1_matrix = np.zeros((num_ind, num_ind), dtype= float)
#temp = combined_data[i, :]
#temp = temp.reshape(num_chromosomes,)
#print(temp)
#print(np.shape(temp))
#print(type(temp))

print("Only Some of These Calculations Are Printed To Show Examples of Calculations\n")

for i in range(len(t1_matrix)):
    
    if i < 1 :
        print("Iteration " +str(i))
        
    for j in range(len(t1_matrix[i])):
       # t1_matrix[i][j] = distance.euclidean(centroid_data[i], centroid_data[j]) 
        ind1 = combined_data[i, :].astype(int)
        #ind1=ind1.reshape(num_chromosomes)
        ind2 = combined_data[j, :].astype(int)
        #ind2=ind2.reshape(num_chromosomes)

        homo_countA = 0   #increment if ind1 = 0 and ind2 = 2
        homo_countB = 0   #incremenet if ind1 = 2 and ind2 = 0
        hetero_count = 0  #increment if ind1 = 1  and ind2 = 1

        for x in range(0, num_chromosomes):
        
          if ind1[x] == 1 and ind2[x] == 1 :

            hetero_count += 1

          if ind1[x] == 0 and ind2[x] == 2 :

            homo_countA += 1

          if ind1[x] == 2 and ind2[x] == 0 :

            homo_countB += 1
      
        if i < 1 and j < 3:
        
            print("Heterozygous Counts For Individual " + str(i) + " & For Individual " + str(j) + " Are " + str(hetero_count))
            print("Homozygous A Counts For Individual " + str(i) + " & For Individual " + str(j) + " Are " + str(homo_countA))
            print("Homozygous B Counts For Individual " + str(i) + " & For Individual " + str(j) + " Are " + str(homo_countB))
        
            print(hetero_count/(homo_countA + homo_countB + hetero_count))

        
        t1_matrix[i][j] = hetero_count/(homo_countA + homo_countB + hetero_count)

print(t1_matrix)
np.savetxt("t1_matrix.csv", t1_matrix, delimiter=",")


Shape of Combined Data is (61, 604184)


Only Some of These Calculations Are Printed To Show Examples of Calculations

Iteration 0
Heterozygous Counts For Individual 0 & For Individual 0 Are 139573
Homozygous A Counts For Individual 0 & For Individual 0 Are 0
Homozygous B Counts For Individual 0 & For Individual 0 Are 0
1.0
Heterozygous Counts For Individual 0 & For Individual 1 Are 53968
Homozygous A Counts For Individual 0 & For Individual 1 Are 13800
Homozygous B Counts For Individual 0 & For Individual 1 Are 13455
0.6644423377614715
Heterozygous Counts For Individual 0 & For Individual 2 Are 53705
Homozygous A Counts For Individual 0 & For Individual 2 Are 13587
Homozygous B Counts For Individual 0 & For Individual 2 Are 13818
0.6621255085686105
[[1.         0.66444234 0.66212551 ... 0.54386701 0.53555356 0.53356349]
 [0.66444234 1.         0.66379214 ... 0.5368363  0.53121869 0.5336263 ]
 [0.66212551 0.66379214 1.         ... 0.53909005 0.52887064 0.5316735 ]
 ...
 [0.54386701 0.

In [14]:
#Load T1_Statistic Matrix

import pprint as p
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

np.set_printoptions(linewidth=np.inf)
t1_matrix = np.loadtxt("t1_matrix.csv", delimiter=',')
p.pprint(t1_matrix)

array([[1.        , 0.66444234, 0.66212551, ..., 0.54386701, 0.53555356, 0.53356349],
       [0.66444234, 1.        , 0.66379214, ..., 0.5368363 , 0.53121869, 0.5336263 ],
       [0.66212551, 0.66379214, 1.        , ..., 0.53909005, 0.52887064, 0.5316735 ],
       ...,
       [0.54386701, 0.5368363 , 0.53909005, ..., 1.        , 0.66894211, 0.6677299 ],
       [0.53555356, 0.53121869, 0.52887064, ..., 0.66894211, 1.        , 0.66041102],
       [0.53356349, 0.5336263 , 0.5316735 , ..., 0.6677299 , 0.66041102, 1.        ]])


In [19]:
# calculate the dissimilarity matrix

disim_matrix = np.zeros((len(t1_matrix), len(t1_matrix)), dtype= float)


for i in range(len(t1_matrix)):
   
    for j in range(len(t1_matrix[i])):

        disim_matrix[i][j] = 1 - t1_matrix[i][j]

print(disim_matrix)
np.savetxt("disim_matrix.csv", disim_matrix, delimiter=",")

[[0.         0.33555766 0.33787449 ... 0.45613299 0.46444644 0.46643651]
 [0.33555766 0.         0.33620786 ... 0.4631637  0.46878131 0.4663737 ]
 [0.33787449 0.33620786 0.         ... 0.46090995 0.47112936 0.4683265 ]
 ...
 [0.45613299 0.4631637  0.46090995 ... 0.         0.33105789 0.3322701 ]
 [0.46444644 0.46878131 0.47112936 ... 0.33105789 0.         0.33958898]
 [0.46643651 0.4663737  0.4683265  ... 0.3322701  0.33958898 0.        ]]


In [20]:
# calculate the dissimilarity matrix part2

#disim_matrix = np.zeros((len(t1_matrix), len(t1_matrix)), dtype= float)


for i in range(len(disim_matrix)):
   
    for j in range(len(disim_matrix[i])):

        disim_matrix[i][j] = np.var(disim_matrix[i] - disim_matrix[j])

print(disim_matrix)
np.savetxt("disim_matrix2.csv", disim_matrix, delimiter=",")

[[0.         0.00370689 0.00548769 ... 0.02473265 0.02176817 0.01797225]
 [0.00425111 0.         0.00551384 ... 0.02497643 0.02188989 0.01798804]
 [0.00428757 0.00642979 0.         ... 0.02497802 0.02197692 0.01803539]
 ...
 [0.00951296 0.01116251 0.01265401 ... 0.         0.01414354 0.01187629]
 [0.00967577 0.01137877 0.01293402 ... 0.00343873 0.         0.01201528]
 [0.00933153 0.01102373 0.01258751 ... 0.00342722 0.00186455 0.        ]]


In [21]:
from numpy.random import randint
from random import random 



ss_t = (np.sum(disim_matrix*disim_matrix))/(2*num_ind)

num_clusters = 4

greeklabels = greek.shape[0]
albanianlabels = albanian.shape[0]
japaneselabels = japanese.shape[0]
koreanlabels = korean.shape[0]
Y = np.vstack ((3*np.ones((albanianlabels,1)), 2*np.ones((greeklabels,1)),np.ones((japaneselabels,1)),np.zeros((koreanlabels,1))))
#Y represents true class assignments from Data




In [22]:
#GA 

best_ssap = 0
final_solutions = []
final_solution_ssap = []

for i in range (0, 50):    #iterate genetic algorithm over 50 populations
    
    solutions = []
    solution_ssap = []
    offspring =[]
    
    for z in range(0, 200):  #generate 200 random guesses at cluster solution
    
        population = []

        for x in range (0, num_ind):

            population.append(randint(0, num_clusters))  

        population = np.asarray(population)               #randomly assign clustering

        albanian_indices = np.where(population == 3)[0]    #indices used to pull data from disim matrix based on cluster assignment
        greek_indices = np.where(population == 2)[0]
        japan_indices = np.where(population == 1)[0]
        korean_indices = np.where(population == 0)[0]

        albanian_data = disim_matrix[:, albanian_indices]    #pull corresponding cluster matrix data for distances
        albanian_data = albanian_data[albanian_indices, :]
        greek_data = disim_matrix[:, greek_indices]
        greek_data = greek_data[greek_indices, :]
        japan_data = disim_matrix[:, japan_indices]
        japan_data = japan_data[japan_indices, :]
        korean_data = disim_matrix[:, korean_indices]
        korean_data = korean_data[korean_indices, :]     

        num_albanians = albanian_data.shape[0]
        num_greeks = greek_data.shape[0]
        num_japanese = japan_data.shape[0]
        num_korean = korean_data.shape[0]

        ss_wp = (((np.sum(albanian_data*albanian_data)))/(2*num_albanians)) + (((np.sum(greek_data*greek_data)))/(2*num_greeks)) + (((np.sum(japan_data*japan_data)))/(2*num_japanese))+ (((np.sum(korean_data*korean_data)))/(2*num_korean))

        ss_ap = ss_t - ss_wp
        
        solutions.append(population.tolist())   #list of cluster assignments
        solution_ssap.append(ss_ap)             # ssap scores
    
    
    if ( i > 0 ) :   #If not first iteration the mutated offspring population gets put into the population with random assignments

        solutions = solutions+final_solutions
        solutions_ssap = solution_ssap + final_solution_ssap
        final_solutions =[]
        final_solution_ssap = []

        

    num_kept_solutions = 75
    selected_indices = sorted(range(len(solution_ssap)), key = lambda sub: solution_ssap[sub])[-num_kept_solutions:]   # get indices of best 75 ssap scores
    selected_indices = np.asarray(selected_indices)
    solutions =  np.asarray(solutions)
    selected_clusters = solutions[selected_indices, :]    #get corresponding cluster assignments with best 75 ssap scores
    
    for a in range(0, len(selected_clusters)):             #single point cross over
    
        cross_point = randint(0,num_ind)                   #random crossover point    
        rand_parent = randint(0,num_kept_solutions)
        parent1 = selected_clusters[a, :]                  #each cluster assignment gets to mate
        parent2 = selected_clusters[rand_parent, :]        #who they mate with is random
        
        
        offspring1 = np.append(parent1[:cross_point], parent2[cross_point:])        #two offspring produced from crossover point
        offspring2 = np.append(parent2[:cross_point], parent1[cross_point:])
        offspring.append(offspring1.tolist())
        offspring.append(offspring2.tolist())

    
    for b in range(0, len(offspring)):
        
        mutation_prob = randint(0, 5)  #20 percent chance of mutation 1/5
        
        if mutation_prob == 1 :      
            
            num_mutations = randint(0, num_ind/10)    #number of individual cluster assingments mutated is random
            
            for c in range(0, num_mutations):
            
                bit_mutations = randint(0, num_ind)
            
                offspring[b][bit_mutations] = randint(0,num_clusters)  

    #Evaluate mutated offspring
    
    for d in range(0, len(offspring)):
        
        final_population = np.asarray(offspring)
        np.savetxt("final_population.csv", final_population, delimiter=",")

        albanian_indices = np.where(final_population[d] == 3)[0]
        greek_indices = np.where(final_population[d] == 2)[0]
        japan_indices = np.where(final_population[d] == 1)[0]
        korean_indices = np.where(final_population[d] == 0)[0]

        albanian_data = disim_matrix[:, albanian_indices]
        albanian_data = albanian_data[albanian_indices, :]
        greek_data = disim_matrix[:, greek_indices]
        greek_data = greek_data[greek_indices, :]
        japan_data = disim_matrix[:, japan_indices]
        japan_data = japan_data[japan_indices, :]
        korean_data = disim_matrix[:, korean_indices]
        korean_data = korean_data[korean_indices, :]

        num_albanians = albanian_data.shape[0]
        num_greeks = greek_data.shape[0]
        num_japanese = japan_data.shape[0]
        num_korean = korean_data.shape[0]

        ss_wp = (((np.sum(albanian_data*albanian_data)))/(2*num_albanians)) + (((np.sum(greek_data*greek_data)))/(2*num_greeks)) + (((np.sum(japan_data*japan_data)))/(2*num_japanese))+ (((np.sum(korean_data*korean_data)))/(2*num_korean))

        ss_ap = ss_t - ss_wp
        
        final_solutions = final_population.tolist()
        final_solution_ssap.append(ss_ap)             #scores
    
    max_index = np.argmax(final_solution_ssap, axis=0)   #find index of where ssap score is highest
    

    if (final_solution_ssap[max_index] > best_ssap):     #compare to current best answer
        best_ssap = final_solution_ssap[max_index]
        print("Best SSAP Score Is " + str(final_solution_ssap[max_index]))
        cluster_solution =[]
        cluster_solution = final_solutions[max_index]
        
        #test accuracy of answer

        Y_test = Y.tolist()
        
        Y_test = sum(Y_test, []) 
        Y_test = [int(i) for i in Y_test] 
        
        correct_counter = 0
        for e in range(0, num_ind):
            if(Y_test[e] == cluster_solution[e]):
                correct_counter+=1
        
 
        accuracy = (correct_counter/num_ind)*100    

        print("\nClustering accuracy is : " + str(accuracy) +"\n")       
        
    
print("Best SSAP Score Was " + str(best_ssap))    
print("\nThe Cluster Solution Was Found to be " + str(cluster_solution))

tcorrect_counter = 0

for i in range(num_ind):
    test_equality  = np.equal(Y[i], cluster_solution[i]) 

    if(all(test_equality)) :
        tcorrect_counter += 1
            
test_accuracy = (tcorrect_counter/num_ind)*100    

print("\nFinal Clustering accuracy is : " + str(test_accuracy))
    


Best SSAP Score Is 0.007291402531090903

Clustering accuracy is : 39.34426229508197

Best SSAP Score Is 0.008215743172240705

Clustering accuracy is : 26.229508196721312

Best SSAP Score Is 0.01050675057538196

Clustering accuracy is : 24.59016393442623

Best SSAP Score Is 0.011214266255675141

Clustering accuracy is : 34.42622950819672

Best SSAP Score Was 0.011214266255675141

The Cluster Solution Was Found to be [2, 1, 2, 2, 0, 2, 2, 0, 2, 2, 0, 1, 2, 2, 1, 2, 0, 2, 1, 2, 1, 1, 2, 3, 2, 1, 0, 1, 1, 0, 1, 1, 0, 3, 3, 0, 3, 1, 0, 1, 3, 0, 1, 0, 0, 0, 1, 0, 1, 3, 1, 3, 1, 0, 3, 1, 1, 1, 1, 3, 1]

Final Clustering accuracy is : 34.42622950819672
